- hosts: basics
  remote_user: ubuntu

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        cache_valid_time: 86400
        upgrade: yes
      become: true

    - name: Install docker dependecies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      become: true

    - name: Create a directory if it does not exist
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
        owner: root
        group: root
      become: true

    - name: Add signing key
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
      become: true

    - name: Add docker repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu focal stable"
        state: present
        filename: docker
      become: true

    - name: Install docker and containerd
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
        state: latest
      become: true

    - name: Configure docker cgroup
      copy:
        src: ./basics/daemon.json
        dest: /etc/docker/daemon.json
      become: true

    - name: Create relative path
      file:
        src: /usr/bin/resolvectl
        dest: /usr/local/bin/resolvconf

    - name: Make sure docker service is active
      service:
        name: docker
        state: started
        enabled: yes
      become: true

    - name: Install kubernetes dependecies
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
        state: present
      become: true

    - name: Get kubernetes keys
      shell: sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg

    - name: Add kubernetes repository
      shell: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

    - name: Install kubernetes
      apt:
        update_cache: yes
        name:
          - kubelet
          - kubeadm
          - kubectl
      become: true

    - name: Hold kubernetes
      dpkg_selections:
        name: "{{item}}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl
      become: true

    - name: Disable memory swap
      shell: |
        swapoff -a
        sudo sed -i '/ swap / s/^/#/' /etc/fstab

    - name: Restart containerd service
      service:
        daemon_reload: yes
        name: containerd
        state: restarted
      become: true
