#update hosts and names
- hosts: etcd[0]
  remote_user: ubuntu
  become: true
  
  environment:
    HOST0: 192.168.0.2
    HOST1: 192.168.0.3
    HOST2: 192.168.0.4
    NAME0: "vps-4263b60e"
    NAME1: "vps-b152d57f"
    NAME2: "vps-a1922212"

  tasks:
  - name: Create tmp directories to store files 
    shell: "mkdir -p /tmp/${HOST0}/ /tmp/${HOST1}/ /tmp/${HOST2}/"

  - name: Copy create credentials file
    copy: src=./etcd/credentials.sh dest=/home/ubuntu mode=a+x

  - name: Create etcd credentials file
    shell: "./credentials.sh"
    
  - name: Run create etcd certs 
    shell: |
      kubeadm init phase certs etcd-ca
      kubeadm init phase certs etcd-server --config=/tmp/${HOST2}/kubeadmcfg.yaml
      kubeadm init phase certs etcd-peer --config=/tmp/${HOST2}/kubeadmcfg.yaml
      kubeadm init phase certs etcd-healthcheck-client --config=/tmp/${HOST2}/kubeadmcfg.yaml
      kubeadm init phase certs apiserver-etcd-client --config=/tmp/${HOST2}/kubeadmcfg.yaml
      cp -R /etc/kubernetes/pki /tmp/${HOST2}/
      # cleanup non-reusable certificates
      find /etc/kubernetes/pki -not -name ca.crt -not -name ca.key -type f -delete
      kubeadm init phase certs etcd-server --config=/tmp/${HOST1}/kubeadmcfg.yaml
      kubeadm init phase certs etcd-peer --config=/tmp/${HOST1}/kubeadmcfg.yaml
      kubeadm init phase certs etcd-healthcheck-client --config=/tmp/${HOST1}/kubeadmcfg.yaml
      kubeadm init phase certs apiserver-etcd-client --config=/tmp/${HOST1}/kubeadmcfg.yaml
      cp -R /etc/kubernetes/pki /tmp/${HOST1}/
      find /etc/kubernetes/pki -not -name ca.crt -not -name ca.key -type f -delete
      kubeadm init phase certs etcd-server --config=/tmp/${HOST0}/kubeadmcfg.yaml
      kubeadm init phase certs etcd-peer --config=/tmp/${HOST0}/kubeadmcfg.yaml
      kubeadm init phase certs etcd-healthcheck-client --config=/tmp/${HOST0}/kubeadmcfg.yaml
      kubeadm init phase certs apiserver-etcd-client --config=/tmp/${HOST0}/kubeadmcfg.yaml
      # No need to move the certs because they are for HOST0
      # clean up certs that should not be copied off this host
      find /tmp/${HOST2} -name ca.key -type f -delete
      find /tmp/${HOST1} -name ca.key -type f -delete

  - name: Fetch etcd2 files from etcd1 to local 
    run_once: yes
    synchronize: src=/tmp/192.168.0.3/ dest=buffer/192.168.0.3 mode=pull

  - name: Fetch etcd3 files from etcd1 to local 
    run_once: yes
    synchronize: src=/tmp/192.168.0.4/ dest=buffer/192.168.0.4 mode=pull

  - name: Remove old config files
    file: path=/home/ubuntu/kubeadmcfg.yaml state=absent

  - name: Move etdc1 files from /tmp to /home/ubuntu 
    copy: remote_src=True src=/tmp/192.168.0.2/kubeadmcfg.yaml dest=/home/ubuntu/

- hosts: etcd[1]
  remote_user: ubuntu
  become: true
  tasks:

  - name: Copy files from local to etcd2 
    synchronize: src=buffer/192.168.0.3/ dest=/home/ubuntu/ mode=push

- hosts: etcd[2]
  remote_user: ubuntu
  become: true
  tasks:

  - name: Copy files from local to etcd3
    synchronize: src=buffer/192.168.0.4/ dest=/home/ubuntu/ mode=push

- hosts: etcd
  remote_user: ubuntu
  become: true
  tasks:

  - name: Configure etcd nodes 
    shell: |    
      chown -R root:root pki
      mv pki /etc/kubernetes/
      kubeadm init phase etcd local --config=kubeadmcfg.yaml
