# - hosts: lb[0]
#   remote_user: ubuntu
#   become: true

#   tasks:
#     - name: Update keepalived config file
#       copy: 
#         src: ./lb/keepalived-lb1.conf
#         dest: /etc/keepalived/keepalived.conf
#         mode: 0644

#     - name: Start keepalived
#       ansible.builtin.systemd:
#         name: "{{item}}"
#         state: restarted
#         enabled: yes
#         masked: no
#       loop: 
#        - keepalived
#        - haproxy