all:
  children:
    basics:
      children:
        master:
          hosts:
            51.161.33.13:
              ansible_ssh_user: ubuntu
            164.132.55.138:
              ansible_ssh_user: ubuntu
        etcd:
          hosts:
            144.217.7.150:
              ansible_ssh_user: ubuntu
            164.132.55.139:
              ansible_ssh_user: ubuntu
            144.217.4.77:
              ansible_ssh_user: ubuntu
        lb:
          hosts:
            144.217.7.150:
              ansible_ssh_user: ubuntu
            164.132.55.139:
              ansible_ssh_user: ubuntu
        worker:
          hosts:
            144.217.5.107:
              ansible_ssh_user: ubuntu
            164.132.55.129:
              ansible_ssh_user: ubuntu
        wireguard-servers:
          hosts:
            144.217.4.77:
              ansible_ssh_user: ubuntu
            51.79.69.211:
              ansible_ssh_user: ubuntu
    wireguard:
      hosts:
        #server
        144.217.4.77:
          ansible_ssh_user: ubuntu
          wireguard_address: "192.168.0.4/24"
          wireguard_port: 52345
          wireguard_endpoint: 15.235.60.92
          wireguard_interface: wg0
          wireguard_allowed_ips: "192.168.0.0/24"
          wireguard_persistent_keepalive: "25"
          wireguard_postup:
            - iptables -A FORWARD -i %i -j ACCEPT
            - iptables -A FORWARD -o %i -j ACCEPT
            - iptables -I FORWARD 1 -i eth0 -o wg0 -j ACCEPT
            - iptables -I FORWARD 1 -i wg0 -o eth0 -j ACCEPT
            - iptables -I INPUT 1 -i eth0 -p udp --dport 52345 -j ACCEPT
            - iptables -A INPUT -s 192.168.0.0/24 -p tcp -m tcp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
            - iptables -A INPUT -s 192.168.0.0/24 -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
          wireguard_postdown:
            - iptables -D FORWARD -i %i -j ACCEPT
            - iptables -D FORWARD -o %i -j ACCEPT
            - iptables -I FORWARD 1 -i eth0 -o wg0 -j ACCEPT
            - iptables -I FORWARD 1 -i wg0 -o eth0 -j ACCEPT
            - iptables -I INPUT 1 -i eth0 -p udp --dport 52345 -j ACCEPT
            - iptables -D INPUT -s 192.168.0.0/24 -p tcp -m tcp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
            - iptables -D INPUT -s 192.168.0.0/24 -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
        #clients
        51.161.33.13:
          ansible_ssh_user: ubuntu
          wireguard_address: "192.168.0.5/32"
          wireguard_port: 52345
          wireguard_interface: wg0
          wireguard_allowed_ips: "192.168.0.5/32"
          wireguard_endpoint: ""
          wireguard_dns: "192.168.0.4, 8.8.8.8, 8.8.4.4"
          wireguard_persistent_keepalive: "25"
        164.132.55.138:
          ansible_ssh_user: ubuntu
          wireguard_address: "192.168.0.6/32"
          wireguard_port: 52345
          wireguard_interface: wg0
          wireguard_allowed_ips: "192.168.0.6/32"
          wireguard_endpoint: ""
          wireguard_dns: "192.168.0.4, 8.8.8.8, 8.8.4.4"
          wireguard_persistent_keepalive: "25"
        144.217.7.150:
          ansible_ssh_user: ubuntu
          wireguard_address: "192.168.0.2/32"
          wireguard_port: 52345
          wireguard_interface: wg0
          wireguard_allowed_ips: "192.168.0.1/32, 192.168.0.2/32"
          wireguard_endpoint: ""
          wireguard_dns: "192.168.0.4, 8.8.8.8, 8.8.4.4"
          wireguard_persistent_keepalive: "25"
        164.132.55.139:
          ansible_ssh_user: ubuntu
          wireguard_address: "192.168.0.3/32"
          wireguard_port: 52345
          wireguard_interface: wg0
          wireguard_allowed_ips: "192.168.0.3/32, 192.168.0.1/32"
          wireguard_endpoint: ""
          wireguard_dns: "192.168.0.4, 8.8.8.8, 8.8.4.4"
          wireguard_persistent_keepalive: "25"
        144.217.5.107:
          ansible_ssh_user: ubuntu
          wireguard_address: "192.168.0.7/32"
          wireguard_port: 52345
          wireguard_interface: wg0
          wireguard_allowed_ips: "192.168.0.7/32"
          wireguard_endpoint: ""
          wireguard_dns: "192.168.0.4, 8.8.8.8, 8.8.4.4"
          wireguard_persistent_keepalive: "25"
        164.132.55.129:
          ansible_ssh_user: ubuntu
          wireguard_address: "192.168.0.8/32"
          wireguard_port: 52345
          wireguard_interface: wg0
          wireguard_allowed_ips: "192.168.0.8/32"
          wireguard_endpoint: ""
          wireguard_dns: "192.168.0.4, 8.8.8.8, 8.8.4.4"
          wireguard_persistent_keepalive: "25"

        # backup server in client only to automate wireguard installation
        51.79.69.211:
          ansible_ssh_user: ubuntu
          wireguard_address: "192.168.0.9/32"
          wireguard_port: 52345
          wireguard_interface: wg0
          wireguard_allowed_ips: "192.168.0.9/32"
          wireguard_endpoint: ""
          wireguard_dns: "192.168.0.4, 8.8.8.8, 8.8.4.4"
          wireguard_persistent_keepalive: "25"
