- hosts: lb[0]
  remote_user: ubuntu
  become: true

  tasks:
    - name: Update keepalived config file
      copy: 
        src: ~/Qubistry/ansible-chainlink/keepalived-lb1.conf
        dest: /etc/keepalived/keepalived.conf
        mode: 0644

    - name: Start keepalived
      ansible.builtin.systemd:
        name: keepalived
        state: started
        enabled: yes
        masked: no