- hosts: all
  remote_user: ubuntu
  become: true

  tasks:
  - name: Update and upgrade apt packages
    apt:
      update_cache: yes
      cache_valid_time: 86400
      upgrade: yes
  - name: Update root user password
    user:
      name: root
      update_password: always
      password: $6$rounds=656000$F6Ha.lAfuB6D0sJ1$onaJQxMltUR6pVBYihmnr6mVBzDUNFCGPqSYhDxfloVb6Fe7A5bk7Bj6zZGHAmtLB9jIcSc5f0OBdGuFelVyF/
  - name: Disable root login via ssh
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: "PermitRootLogin no"
      state: present
      backup: yes
    notify:
      - restart ssh
  - name: Install fail2ban
    apt: 
      name: fail2ban
      state: latest
      update_cache: yes
      cache_valid_time: 3600

  handlers:
  - name: restart ssh
    service:
      name: sshd 
      state: restarted
