#run after post-vpn-config.yaml
- hosts: wireguard-servers
  remote_user: ubuntu
  become: true

  tasks:
   - name: Create keepalived group and user
     user:
       name: keepalived_script
       groups: keepalived_script
       shell: /sbin/nologin
       append: yes

   - name: Update keepalived files to master server 
     copy: src={{ item.src }} dest={{ item.dest }} 
     with_items:
       - { src: './server-vpn-backup/keepalived1.conf' , dest: '/etc/keepalived/keepalived.conf' }
       - { src: './server-vpn-backup/check_vpnserver.sh' , dest: '/etc/keepalived/check_vpnserver.sh' }
       - { src: './server-vpn-backup/checkserver.service' , dest: '/etc/systemd/system/checkserver.service' }
       - { src: './server-vpn-backup/checkserver.sh' , dest: '/home/ubuntu/bin/checkserver.sh' }
       - { src: './server-vpn-backup/master1.py' , dest: '/home/ubuntu/bin/master.py' }
     when: " inventory_hostname == 'vps-a1922212' "
         
   - name: Update keepalived files to backup server 
     copy: src={{ item.src }} dest={{ item.dest }} 
     with_items:
       - { src: './server-vpn-backup/keepalived2.conf' , dest: '/etc/keepalived/keepalived.conf' }
       - { src: './server-vpn-backup/check_vpnserver.sh' , dest: '/etc/keepalived/check_vpnserver.sh' }
       - { src: './server-vpn-backup/checkserver.service' , dest: '/etc/systemd/system/checkserver.service' }
       - { src: './server-vpn-backup/checkserver.sh' , dest: '/home/ubuntu/bin/checkserver.sh' }
       - { src: './server-vpn-backup/master2.py' , dest: '/home/ubuntu/bin/master.py' }
     when: " inventory_hostname == 'vps-e7d30833' "

         
   - name: Enable services 
     systemd:
      daemon_reload: yes
      name: "{{ item }}"
      state: restarted
     loop:
      - keepalived 
      - checkserver.service


      