apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume-1
  labels:
    type: local
    app: postgresql-db
spec:
  storageClassName: manual
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume-2
  labels:
    type: local
    app: postgresql-db
spec:
  storageClassName: manual
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
